### ISSUE TITLE
Support of inheritdoc tag

### ISSUE THREAD

**Issue by jadaml** [OJacot-Descombes/PrettyDocComments#4]
Version: 0.3.4
I have noticed, that the extension does not support the `<inheritdoc/>` tag:

    class MyBaseClass
    {
        /// <summary>This is where all the magic happens.</summary>
        public virtual void DoMagic()
        {
            // ...
        }
    }

    class MySubClass : MyBaseClass
    {
        /// <inheritdoc/> 
        public override void DoMagic()
        {
            // ...
        }
    }

![Screenshot 2023-09-26 160246](https://github.com/OJacot-Descombes/PrettyDocComments/assets/1237806/e7acc7d1-4906-4b1a-9792-ec8d809f3a65)
![Screenshot 2023-09-26 160353](https://github.com/OJacot-Descombes/PrettyDocComments/assets/1237806/9ef1e6e1-4fe9-4238-a583-834187b36acc)

**Comment by OJacot-Descombes** [comment]
I know. The problem is that I don't use the Roslyn compiler to analyze the code but only do a string search for "///". The advantage is that the same code works for C#, C++ and F# and by checking for "'''", also for VB. The disadvantage is that I don't have access to the type information required to do this kind of substitution.

So, there is no quick fix I can make. But bear in mind that I don't try to create the end-documentation, as e.g. [Sandcastle](https://en.wikipedia.org/wiki/Sandcastle_(software)) would do, by also enhancing the doc with type information, listing implemented interfaces, etc. . Instead, this extension only displays the source of the documentation, i.e., the XML, in a nicer way.

**Does someone have an idea on how this &lt;inheritdoc&gt; could be implemented?** (for all the mentioned programming languages)

**Comment by jadaml** [comment]
Considering how fast you display the formatted documentation, I've realized something like that is happening. As I see this, you would need to parse the language to a degree to know the inheritance of the class and figure out what documentation block to display when the user invokes `inheritdoc`. I've never used it as such, but in theory, an `inheritdoc` could also appear with other tags, but don't know how it works then.

Maybe you could cheat if the user is already creating the documentation XML, and read the final XML file back, but this could not work in all case.

**Comment by wekempf** [comment]
I'm OK with not fully support `<inheritdoc/>` since IntelliSense will already provide this support. What I would like is maybe some different formatting. Maybe a different background color, slightly smaller font, and have the summary read something like "Documentation inherited from base" rather than "inheritdoc()".

**Comment by OJacot-Descombes** [comment]
@wekempf: the Tools / Options dialog supports changing the background color, the font size and other things. I prefer not to translate "inheritdoc()" by an English sentence. "inheritdoc" will be more understandable for people speaking other languages, as, while not translated, corresponds at least to the tag name.

![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/8210a3f7-6831-4784-8877-b6061a96b762)
