### ISSUE TITLE
Visual display when selecting text

### ISSUE THREAD

**Issue by wekempf** [OJacot-Descombes/PrettyDocComments#6]
When moving/placing the cursor inside the comments the visual display is nicely hidden, however, if you select text and the cursor moves outside of the comment the visual display does not remain hidden. Basically, if any portion of the selection is within the comment the visual display should be hidden and the comment text should be visible.

**Comment by OJacot-Descombes** [comment]
Good idea. I will look into this.

However, If you select a lot of lines and one or several comments happen to be inside the selection (by accident), then probably the comments should still be visible. Maybe the comment should be hidden only if either the start or the end of the selection is in the comment, because this means that we are probably editing something related to the comment. What do you think?

**Comment by OJacot-Descombes** [comment]
New in version 0.3.5: In addition to the text caret, now the text selection start and end also determine the visibility of the pretty comment.
