### ISSUE TITLE
Blank lines are ignored

### ISSUE THREAD

**Issue by APrettyCoolProgram** [OJacot-Descombes/PrettyDocComments#8]
Super cool extension.

One thing I occasionally do with my XML comments is write detailed `<remarks>`

For example:

```
/// <remarks>
/// This method does a thing.
/// 
/// When using this method, keep in mind:
/// * Thing one
/// * Thing two
/// * Thing three
/// </remarks>
```

This is displayed as:

```
Remarks
This method does a thing. When using this method, keep in mind: * Thing one * Thing two * Thing three
```

**Comment by OJacot-Descombes** [comment]
You can do it with a bulleted list
```
/// <list type="bullet">
/// <item>
/// <term>Add</term>
/// <description>Addition Operation</description>
/// </item>
/// <item>
/// <term>Subtract</term>
/// <description>Subtraction Operation</description>
/// </item>
/// <item>
/// <term>Multiply</term>
/// <description>Multiplication Operation</description>
/// </item>
/// <item>
/// <term>Divide</term>
/// <description>Division Operation</description>
/// </item>
/// </list>
```
It displays as
![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/d782dd93-90de-4c10-b7df-d02e8be6cb98)

Or simply
```
/// <ul>
///  <li>Beetroot</li>
///  <li>Ginger</li>
///  <li>Potato</li>
///  <li>Radish</li>
/// </ul>
```
which disaplys as:
![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/20b2d06d-a644-4ddd-893e-7e2910ef62f3)

Or you can add line-breaks `<br />` as in
```
/// * Thing one<br />
/// * Thing two<br />
/// * Thing three
```
Or enclose the lines in `<para> </para>`. However, this will create a space between the lines.

Note that your remark items will not only be displayed on one line in this extension but also in IntelliSense. I don't want to introduce a new syntax since I already interpret a lot of HTML stuff.
